import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import BlogLanding from '../components/blog/blog-landing.jsx'
import SearchQuery from '../components/blog/search-query.jsx'
const inter = Inter({ subsets: ['latin'] })

export default function Blog() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.blog}>
        <div className="blog-page-wrapper">
            <BlogLanding> </BlogLanding>
            <SearchQuery> </SearchQuery>
        </div>
      </main>
    </>
  )
}
