import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import Test from '../components/test.jsx'
const inter = Inter({ subsets: ['latin'] })

export default function TestDev() {
  return (
    <>
      <Head>
        <title>DEVELOPMENT</title>
        <meta name="description" content="Generated by create next app" />

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.testdev}>
        <div className="testdev-page-wrapper">
            <Test> </Test>
        </div>
      </main>
    </>
  )
}
